[package]
name = "cyto-ibu-count"
version = "0.2.0"
edition = "2024"
license = "BSD-3-Clause"
authors = ["Noam Teyssier"]
description = "Ultra high-throughput processing of 10x-flex single-cell sequencing data"
repository = "https://github.com/noamteyssier/cyto"
categories = ["command-line-utilities", "science::bioinformatics"]
keywords = ["flex", "binseq", "single-cell", "probe", "sequencing"]

[dependencies]
anyhow = { workspace = true }
bitnuc = { workspace = true }
csv = { workspace = true }
cyto-cli = { workspace = true }
cyto-io = { workspace = true }
ibu = { workspace = true }
log = { workspace = true }
hashbrown = { workspace = true }
serde = { workspace = true }

gzp = "2.0.2"
thiserror = "2.0.18"

[lints]
workspace = true
